### ISSUE TITLE
datashield.workspace functions and opal objects created with key pairs

### ISSUE THREAD

**Issue by tombisho** [datashield/opal#12]
I am having trouble using the datashield.workspace functions with opal objects that were created using key pairs rather than a username and password. When using keys, the opal object does not have a value in the username field. This throws an error.

It might be that these functions are not intended for use with key pairs, in which case this could be closed. We would like to move away from using the key pair log in as it is not convenient for users, but never got around the issue of being certain a man in the middle attack won't occur for sites not using a signed certificate...

**Comment by ymarcon** [comment]
That would be an easy fix as we already [get the subject profile](https://github.com/datashield/opal/blob/master/R/opal.r#L628) to verify the connection credentials. Instead of ignoring it, we could extract the username from it.

**Comment by tombisho** [comment]
Thanks!

**Comment by ymarcon** [comment]
2.6.1 is available in https://cran.obiba.org
