### ISSUE TITLE
Is it really possible to execute arbitrary R code on any Opal server after logging in?

### ISSUE THREAD

**Issue by stefan-m-lenz** [datashield/opal#8]
After reading the code in `opal.r`, I installed the DataSHIELD client and successfully executed the following commands (among others):

    o <- opal.login(username='administrator',password='password',url='https://opal-demo.obiba.org')
    opal.execute(o, script = "getwd()")
    opal.execute(o, script = "readLines('../../../conf/logback.xml')
    opal.execute(o, script = "file.create('You are hacked')")

Is it really possible to execute arbitrary R commands after you are logged in on an Opal server? Aren't all doors open then for anyone who knows a password?

**Comment by ymarcon** [comment]
In the example you give, the user is the administrator and therefore has full rights on the server.
A normal "datashield" user would not be allowed to do that.

**Comment by stefan-m-lenz** [comment]
OK, it is very generous to get administrator rights on the server for testing. It seems you trust your test users really much!

**Comment by ymarcon** [comment]
The opal user might be given or not the right to execute R commands, but in the end the R command is execute by the user that runs the R server, which has very limited (unix) rights. Your example shows that a file can be created, but it is in the R session workspace limit.
