### ISSUE TITLE
SSL issues under Win 10

### ISSUE THREAD

**Issue by kkmann** [datashield/opal#9]
Hi, 

I am struggling with opal.login under Windows 10. I can log in to the Opal server via the web interface perfectly fine and use the R interface from Ubuntu but when invoking opal.login under Windows 10, I get

    Error in function (type, msg, asError = TRUE)  : 
        error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

So far, my guess is that this is related to the Rcurl package being hopelessly outdated (curl 7.40 and openssl 1.0.0). In particular, this setup does not support TLS 1.1 or 1.2. Any idea on how to address this issue? Is there a chance that opal could switch to using the curl package which seems to be much better maintained?

```
> RCurl::curlVersion()
$age
[1] 3

$version
[1] "7.40.0"

$vesion_num
[1] 468992

$host
[1] "x86_64-pc-win32"

$features
      ssl      libz      ntlm asynchdns    spnego largefile       idn      sspi 
        4         8        16       128       256       512      1024      2048 

$ssl_version
[1] "OpenSSL/1.0.0o"

$ssl_version_num
[1] 0

$libz_version
[1] "1.2.8"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps" 
[10] "ldap"   "pop3"   "pop3s"  "rtmp"   "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ares
[1] ""

$ares_num
[1] 0

$libidn
[1] ""
```

```
> curl::curl_version()
$version
[1] "7.59.0"

$ssl_version
[1] "(OpenSSL/1.0.2n) WinSSL"

$libz_version
[1] "1.2.8"

$libssh_version
[1] "libssh2/1.8.0"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps" 
[10] "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE
```

**Comment by ymarcon** [comment]
Hi, thanks for the report, I was not aware that RCurl was not maintained anymore. The curl package seems to be the way to go.

**Comment by ymarcon** [comment]
curl package is too low level. httr (based on curl) should be used instead.

**Comment by kkmann** [comment]
Any news on this issue? I doubt that I could migrate the entire package to httr myself.

**Comment by ymarcon** [comment]
This requires quite some work and testing (rjson is to be replaced by jsonlite that comes with httr). I have recently developed the [micar](https://github.com/obiba/micar) package based on httr+jsonlite. This experience can help. I will try to migrate opal by the end of next week.

**Comment by ymarcon** [comment]
By the way, do you use the datashield functions of the package?

**Comment by ymarcon** [comment]
Package rewrite using httr in place of RCurl done in the fork: [obiba/opalr](https://github.com/obiba/opalr)
